export const WORLD_DATA = {
  virtualResolution: {
    width: 1280,
    height: 1280,
  },
  player: {
    radius: 18,
    speed: 320,
    maxHp: 5,
    hitInvulnerabilitySec: 0.65,
  },
  enemy: {
    radius: 16,
    speed: 118,
    maxHp: 3,
    contactDamage: 1,
    color: "#ff7f90",
  },
  weapon: {
    fireIntervalSec: 0.34,
    projectileSpeed: 620,
    projectileRadius: 6,
    projectileDamage: 1,
    projectileLifetimeSec: 1.6,
    projectileColor: "#ffd56b",
  },
  xp: {
    gemRadius: 7,
    gemColor: "#63c0ff",
    gemValue: 1,
    pickupBaseRadius: 64,
    pickupAttractRadius: 150,
    pickupSpeed: 420,
    levelBaseXp: 5,
    levelStepXp: 3,
  },
  spawn: {
    startDelaySec: 0.45,
    baseIntervalSec: 0.8,
    minIntervalSec: 0.2,
    accelerationPerSec: 0.018,
    minDistance: 460,
    maxDistance: 760,
    maxEnemies: 160,
  },
  stage: {
    durationSec: 600,
    enemyHpScaleAtEnd: 2.2,
    enemySpeedScaleAtEnd: 1.45,
    enemyDamageScaleAtEnd: 2.0,
  },
  weaponDefs: [
    {
      id: "bolt_wand",
      label: "Bolt Wand",
      kind: "target_single",
      maxLevel: 8,
      baseDesc: "Auto shoots nearest enemy",
      levels: [
        { interval: 0.34, damage: 1, speed: 620, size: 6, life: 1.6, color: "#ffd56b" },
        { interval: 0.31, damage: 1, speed: 640, size: 6, life: 1.6, color: "#ffd56b" },
        { interval: 0.29, damage: 2, speed: 660, size: 6, life: 1.7, color: "#ffe17b" },
        { interval: 0.27, damage: 2, speed: 690, size: 7, life: 1.7, color: "#ffe17b" },
        { interval: 0.25, damage: 3, speed: 720, size: 7, life: 1.8, color: "#ffef95" },
        { interval: 0.23, damage: 3, speed: 750, size: 8, life: 1.8, color: "#ffef95" },
        { interval: 0.21, damage: 4, speed: 790, size: 8, life: 1.9, color: "#fff4ad" },
        { interval: 0.19, damage: 4, speed: 830, size: 9, life: 2.0, color: "#fff4ad" },
      ],
    },
    {
      id: "twin_fangs",
      label: "Twin Fangs",
      kind: "target_dual",
      maxLevel: 8,
      baseDesc: "Two parallel shots",
      levels: [
        { interval: 0.74, damage: 1, speed: 560, size: 5, life: 1.5, color: "#8cf6ff", laneOffset: 10 },
        { interval: 0.68, damage: 1, speed: 590, size: 5, life: 1.55, color: "#8cf6ff", laneOffset: 11 },
        { interval: 0.62, damage: 2, speed: 610, size: 5, life: 1.6, color: "#9cf8ff", laneOffset: 11 },
        { interval: 0.57, damage: 2, speed: 640, size: 6, life: 1.65, color: "#9cf8ff", laneOffset: 12 },
        { interval: 0.53, damage: 2, speed: 680, size: 6, life: 1.7, color: "#affbff", laneOffset: 13 },
        { interval: 0.49, damage: 3, speed: 710, size: 6, life: 1.8, color: "#affbff", laneOffset: 14 },
        { interval: 0.45, damage: 3, speed: 740, size: 7, life: 1.9, color: "#c4fdff", laneOffset: 15 },
        { interval: 0.42, damage: 4, speed: 780, size: 7, life: 2.0, color: "#c4fdff", laneOffset: 16 },
      ],
    },
    {
      id: "fan_shot",
      label: "Fan Shot",
      kind: "target_spread",
      maxLevel: 8,
      baseDesc: "Multi-shot spread",
      levels: [
        { interval: 0.95, damage: 1, speed: 520, size: 5, life: 1.4, color: "#ffb36f", shots: 3, spreadDeg: 22 },
        { interval: 0.89, damage: 1, speed: 540, size: 5, life: 1.45, color: "#ffb36f", shots: 3, spreadDeg: 26 },
        { interval: 0.84, damage: 1, speed: 560, size: 5, life: 1.5, color: "#ffbe81", shots: 4, spreadDeg: 30 },
        { interval: 0.78, damage: 2, speed: 580, size: 5, life: 1.55, color: "#ffbe81", shots: 4, spreadDeg: 34 },
        { interval: 0.72, damage: 2, speed: 610, size: 6, life: 1.6, color: "#ffc791", shots: 5, spreadDeg: 36 },
        { interval: 0.67, damage: 2, speed: 640, size: 6, life: 1.65, color: "#ffc791", shots: 5, spreadDeg: 40 },
        { interval: 0.62, damage: 3, speed: 670, size: 6, life: 1.7, color: "#ffd2a6", shots: 6, spreadDeg: 42 },
        { interval: 0.58, damage: 3, speed: 700, size: 7, life: 1.8, color: "#ffd2a6", shots: 6, spreadDeg: 46 },
      ],
    },
    {
      id: "nova_ring",
      label: "Nova Ring",
      kind: "radial_burst",
      maxLevel: 8,
      baseDesc: "Fires in all directions",
      levels: [
        { interval: 1.6, damage: 1, speed: 440, size: 5, life: 1.1, color: "#b3ff8d", shots: 8 },
        { interval: 1.45, damage: 1, speed: 470, size: 5, life: 1.15, color: "#b3ff8d", shots: 8 },
        { interval: 1.32, damage: 2, speed: 500, size: 5, life: 1.2, color: "#c0ff9d", shots: 10 },
        { interval: 1.2, damage: 2, speed: 530, size: 6, life: 1.25, color: "#c0ff9d", shots: 10 },
        { interval: 1.08, damage: 2, speed: 560, size: 6, life: 1.3, color: "#cdffac", shots: 12 },
        { interval: 0.98, damage: 3, speed: 590, size: 6, life: 1.35, color: "#cdffac", shots: 12 },
        { interval: 0.9, damage: 3, speed: 620, size: 7, life: 1.4, color: "#dcffbd", shots: 14 },
        { interval: 0.82, damage: 4, speed: 650, size: 7, life: 1.5, color: "#dcffbd", shots: 16 },
      ],
    },
    {
      id: "meteor_slug",
      label: "Meteor Slug",
      kind: "heavy_single",
      maxLevel: 8,
      baseDesc: "Slow heavy shots",
      levels: [
        { interval: 1.05, damage: 4, speed: 420, size: 10, life: 2.0, color: "#ff6f8f" },
        { interval: 0.98, damage: 4, speed: 450, size: 10, life: 2.0, color: "#ff6f8f" },
        { interval: 0.92, damage: 5, speed: 470, size: 11, life: 2.1, color: "#ff7e9b" },
        { interval: 0.86, damage: 5, speed: 500, size: 11, life: 2.1, color: "#ff7e9b" },
        { interval: 0.8, damage: 6, speed: 530, size: 12, life: 2.2, color: "#ff8ea8" },
        { interval: 0.75, damage: 7, speed: 560, size: 12, life: 2.2, color: "#ff8ea8" },
        { interval: 0.7, damage: 8, speed: 590, size: 13, life: 2.3, color: "#ffa1b6" },
        { interval: 0.65, damage: 9, speed: 620, size: 14, life: 2.4, color: "#ffa1b6" },
      ],
    },
  ],
  passiveDefs: [
    {
      id: "might",
      label: "Might",
      maxLevel: 5,
      baseDesc: "Projectile damage up",
      levels: [
        { damageMul: 1.1 },
        { damageMul: 1.1 },
        { damageMul: 1.1 },
        { damageMul: 1.1 },
        { damageMul: 1.1 },
      ],
    },
    {
      id: "haste",
      label: "Haste",
      maxLevel: 5,
      baseDesc: "Attack speed up",
      levels: [
        { hasteMul: 1.08 },
        { hasteMul: 1.08 },
        { hasteMul: 1.08 },
        { hasteMul: 1.08 },
        { hasteMul: 1.08 },
      ],
    },
    {
      id: "swiftness",
      label: "Swiftness",
      maxLevel: 5,
      baseDesc: "Move speed up",
      levels: [
        { moveSpeedMul: 1.08 },
        { moveSpeedMul: 1.08 },
        { moveSpeedMul: 1.08 },
        { moveSpeedMul: 1.08 },
        { moveSpeedMul: 1.08 },
      ],
    },
    {
      id: "vitality",
      label: "Vitality",
      maxLevel: 5,
      baseDesc: "Max HP up + heal",
      levels: [
        { maxHpAdd: 1, heal: 1 },
        { maxHpAdd: 1, heal: 1 },
        { maxHpAdd: 1, heal: 1 },
        { maxHpAdd: 1, heal: 1 },
        { maxHpAdd: 2, heal: 2 },
      ],
    },
    {
      id: "magnet",
      label: "Magnet",
      maxLevel: 5,
      baseDesc: "Pickup radius up",
      levels: [
        { magnetAdd: 22 },
        { magnetAdd: 24 },
        { magnetAdd: 26 },
        { magnetAdd: 28 },
        { magnetAdd: 32 },
      ],
    },
    {
      id: "ballistics",
      label: "Ballistics",
      maxLevel: 5,
      baseDesc: "Projectile speed up",
      levels: [
        { projectileSpeedMul: 1.12 },
        { projectileSpeedMul: 1.12 },
        { projectileSpeedMul: 1.12 },
        { projectileSpeedMul: 1.12 },
        { projectileSpeedMul: 1.12 },
      ],
    },
    {
      id: "overcharge",
      label: "Overcharge",
      maxLevel: 5,
      baseDesc: "Projectile size up",
      levels: [
        { projectileSizeMul: 1.1 },
        { projectileSizeMul: 1.1 },
        { projectileSizeMul: 1.1 },
        { projectileSizeMul: 1.1 },
        { projectileSizeMul: 1.1 },
      ],
    },
    {
      id: "guard",
      label: "Guard",
      maxLevel: 5,
      baseDesc: "Reduce contact damage",
      levels: [
        { damageTakenMul: 0.92 },
        { damageTakenMul: 0.92 },
        { damageTakenMul: 0.92 },
        { damageTakenMul: 0.92 },
        { damageTakenMul: 0.92 },
      ],
    },
  ],
};
